Try exit

diff --git a/.github/workflows/DeployRelease.yaml b/.github/workflows/DeployRelease.yaml
--- a/.github/workflows/DeployRelease.yaml
+++ b/.github/workflows/DeployRelease.yaml
@@ -15,6 +15,15 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Validate release tag 
+        id: validate-release-tag
+        run: |
+          TAG_REGEX='^v([0-9]+\.){2}(\*|[0-9]+)(-.*)?$'
+          if [[ ! ${{ github.event.release.tag_name }} =~ $TAG_REGEX ]]; then
+            echo "Invalid tag name: ${{ github.event.release.tag_name }}"
+            exit 1
+          fi
+
       - name: Get commit SHA for release
         id: get-commit-sha
         run: echo "sha=sha-$(git rev-parse --short=7 HEAD~)" >> $GITHUB_OUTPUT
